### PR TITLE
Update install.sh

### LINKED ISSUE #3: Fix docker install
- Fix docker install in ` install.sh` for Linux based on Debian
- If Linux mint, use bionic on `add-apt-repository`

### PR DESCRIPTION
**Pull request by hrshbh**
Fixes #3 
Test this on your workstation.
add-apt-repository seems OK, although I have not verified the link.

### CODE REVIEW

**Review by henriquepw — CHANGES_REQUESTED** [review]
Can you fix the docker too?

**Comment by hrshbh** [comment]
What is the issue in Docker exactly?

**Comment by henriquepw** [comment]
I think it's just the `if`, when the distribution was Ubuntu, use `lsb_release -cs` if mint use` bionic`

**Comment by hrshbh** [comment]
Sorry for too many commits...

**Comment by henriquepw** [comment]
it's fine!

**Pull request merged**
